Repository sparcs-kaist/zabo-front-reactjs, pull requests merged in 2020-01, with the labels that each got.

#26 Feature/user profile
  .eslintrc
  src/components/pages/ProfilePage/Profile.styled.js
  src/components/pages/ProfilePage/ProfileUserPage.js
  src/static/images/defaultProfile.png
  src/static/images/groupDefaultProfile.png
  yarn.lock
Labels: UI, feature

#29 Feature/image process
  src/components/templates/ZaboUpload/UploadImages.js
  src/components/templates/ZaboUpload/UploadProcess.js
  src/lib/utils/index.js
Labels: feature

#31 Feature/image process
  package.json
  src/boot.js
  src/components/pages/ZaboUploadPage/ZaboUploadPage.js
  src/components/pages/index.js
  src/components/templates/Header/Header.js
  src/components/templates/ZaboUpload/SelectGroup.js
  src/components/templates/ZaboUpload/UploadImages.js
  src/hooks/useSetState.js
  yarn.lock
Labels: enhancement

#36 Fix/upload
  package.json
  src/components/pages/ZaboUploadPage/ZaboUploadPage.js
  src/components/templates/ZaboUpload/UploadImages.js
  src/components/templates/ZaboUpload/grid-layout.scss
  yarn.lock
Labels: fix

#46 Feature/views
  package.json
  src/components/templates/ZaboUpload/UploadImages.js
  src/lib/axios.js
  src/setupProxy.js
  yarn.lock
Labels: feature

#56 feat(editor): Replace editor with Quill
  package.json
  src/components/atoms/InputBase/InputBase.js
  src/components/organisms/StyledQuill.js
  src/components/pages/ZaboPage/ZaboPage.js
  src/components/templates/ZaboUpload/InfoForm.js
  src/components/templates/ZaboUpload/InfoForm.styled.js
  yarn.lock
Labels: enhancement
